### ISSUE TITLE
[Research] Updating BLOCK_PERIOD

### ISSUE THREAD

**Issue by ChainSafeSystems** [goerli/eips-poa#9]
- [ ] adding mainnet like dynamic block times through a Gaussian distribution of some kind 
- [ ] ...edit and add more...

**Comment by soc1c** [comment]
> do I understand that you'd like something akin to actual `block_time = period + r` where `r` is a uniform random value in `[-period/2, 3*period/2]`?

> if we do uniform random, then the average block time will hover around `1.5*period`, which imho is wrong

> I'm also on the opinion that uniform random is not appropriate, I'd go with gauss or poisson distributions to reflect hiccups vs. regular drifts

> Our idea for the hackathon (please let us know what you think) is to extend clique to mimic mainnet conditions. Specifically the two  main differences we see affecting developers are BLOCK_PERIOD and SIGNER_LIMIT. As you mentioned earlier a way to  change BLOCK_PERIOD to mimic mainnet conditions is through a Gaussian distribution or something like that. With SIGNER_LIMIT sometimes halting the blockchain we think we can mimic mainnet conditions by making the process a bit more dynamic, with the limit depending on the current online validators. We are obviously assuming that these validators are not malicious actors.

**Comment by soc1c** [comment]
Updating block timestamp to not require block period at all.

**Comment by soc1c** [comment]
2c56eec787cdfd65ff8d87007645391847dac664 proposes

  * **`timestamp`**: It **must** be greater than the parent timestamp.

_(instead of including BLOCK_PERIOD)_

249ebbc05a12f3bd577b0fbab0bbc8a43211a5d8 proposes

* Calculate the Gaussian random signing time of the next block (parent + **`BLOCK_PERIOD + r`**, where `r` is an uniform random value in `[-BLOCK_PERIOD/4, BLOCK_PERIOD/4]`).
